---
#- name: "Include {{ ansible_facts['distribution'] }} {{ shell }} shell specific tasks"
#  include_tasks: "{{ ansible_facts['distribution'] | replace(' ', '') }}/{{ shell }}.yml"

- name: "Install {{ shell }} shell"
  become: true
  ansible.builtin.package:
    name: "{{ shell }}"
    state: present
  
- name: Get the path to shell
  become: true
  ansible.builtin.shell: which {{ shell }}
  register: shell_path

- name: Ensure shell is in allowed shells
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ shell_path.stdout }}"
  when: shell_path is not skipped

- name: Set shell as the default shell
  become: true
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "{{ lookup('pipe', shell_path.stdout) }}"
  when: shell_path is not skipped
  notify:
    - Restart session
