---
- hosts: localhost
  vars:
    asdf_plugins:
      - nodejs
      - python
      - ruby
      - terraform
    # asdf_yarn_packages:
    #   - react-native-cli
    #   - create-react-app
    #   - apollo
    #   - generator-generator
    #   - yo
    dotfiles_repo: "https://github.com/mat-green/dotfiles.git"
    dotfiles_repo_version: main
    dotfiles_files:
      - .zshrc.personal.before
      - .zshrc.personal.after
    homebrew_cask_apps:
      - temurin # AKA java, password
      #- 1password
      - adobe-acrobat-reader # password
      - apache-directory-studio
      # - android-sdk
      # - android-studio
      - canon-captureontouch-utility # password
      # - datagrip
      - drawio
      - docker
      - dropbox
      # - figma
      - firefox
      - flux
      - gimp
      - google-chrome
      # - google-cloud-sdk
      - grammarly
      - kindle
      - iterm2
      - lastpass
      - lens
      - leocad
      - libreoffice
      - logseq
      # - ngrok
      - paragon-ntfs # Gpassword
      - rescuetime
      - signal
      - slack
      - spotify
      - steam
      - telegram
      - ubiquiti-unifi-controller # Password
      - vlc
      - virtualbox # Password
      - visual-studio-code
      - whatsapp
      - zoom
    homebrew_installed_packages:
      # - autoconf
      # - automake
      # - aws-iam-authenticator
      # - awscli
      # - bfg
      # - curl
      # - fzf
      # - git
      # - gpg
      - htop
      # - imagemagick@6
      # - kubectx
      # - kubernetes-cli
      # - kubernetes-helm
      # - libtool
      # - libxslt
      # - libyaml
      - mas
      # - openssl
      # - pkg-config
      - packer
      - postgresql
      #- pgadmin4 # Manual as if fails for some reason
      - pnpm
      # - redis
      # - sqlite3
      # - terraform
      - terraform-ls
      # - unixodbc
      - unzip
      #- vivaldi # Manual as if fails for some reason
      # - vim
      # - watchman
      # - xy
      # - zlib
      - zsh
    homebrew_uninstalled_packages: []
    homebrew_taps:
      - homebrew/cask-drivers
      - homebrew/cask-versions
    mas_signin_dialog: true
    mas_installed_apps:
      - { id: 406056744, name: "Evernote (7.14)" }
      - { id: 402592703, name: "Time Out (2.6.2)" }
      # - { id: 497799835, name: "Xcode (12.0.1)" }
      - { id: 1261265709, name: "NTFS Assistant (3.0)" }
      - { id: 441258766, name: "Magnet (2.4.9)" }
    mas_uninstalled_apps:
      - { id: 408981434, name: "iMovie" }
      - { id: 409183694, name: "Keynote" }
      - { id: 409201541, name: "Pages" }
      - { id: 409203825, name: "Numbers" }
      - { id: 682658836, name: "GarageBand" }
    vscode_extensions:
      # - apollographql.vscode-apollo
      # - bradlc.vscode-tailwindcss
      # - castwide.solargraph
      - clinyong.vscode-css-modules
      # - jakebecker.elixir-ls
      # - kaiwood.endwise
      # - karunamurti.haml
      # - ms-vscode-remote.vscode-remote-extensionpack
      - msjsdiag.debugger-for-chrome
      # - rebornix.ruby
      - richie5um2.vscode-sort-json
      - Tyriar.sort-lines
      # - vscodevim.vim
      - wholroyd.jinja
      # - wingrunr21.vscode-ruby
      - streetsidesoftware.code-spell-checker
      - fabiospampinato.vscode-todo-plus
      - alphabotsec.vscode-eclipse-keybindings
      # move to settings - CoenraadS.bracket-pair-colorizer
      - dbaeumer.vscode-eslint
      - eamodio.gitlens
      - EditorConfig.EditorConfig
      # - Equinusocio.vsc-community-material-theme
      # - Equinusocio.vsc-material-theme
      # - equinusocio.vsc-material-theme-icons
      - esbenp.prettier-vscode
      # - GitHub.github-vscode-theme
      - hashicorp.terraform
      - jtavin.ldif
      - lextudio.restructuredtext
      - mrmlnc.vscode-autoprefixer
      - ms-python.python
      - ms-python.vscode-pylance
      - octref.vetur
      # - philipbe.theme-gray-matter
      - qinjia.seti-icons
      - redhat.vscode-yaml
      - ritwickdey.LiveServer
      - RomanPeshkov.vscode-text-tables
      - Shan.code-settings-sync
      - tomoki1207.pdf
      - trond-snekvik.simple-rst
      - TsumiNa.Seti-theme
      - vincaslt.highlight-matching-tag
      - vscode-icons-team.vscode-icons
      - xabikos.JavaScriptSnippets
      - yzhang.markdown-all-in-one

# Need to stop the mac from sleeping, see http://www.rawinfopages.com/mac/how-to-customise-power-settings-terminal-mac, during the install.
  roles:
    - asdf
    - geerlingguy.mac.homebrew
    - homebrew
    - geerlingguy.mac.mas
    - vscode
    - oh-my-zsh
    - geerlingguy.dotfiles
