---
- hosts: localhost
  vars:
    asdf_plugins:
      - nodejs
      - python
      - ruby
      - terraform
    # asdf_yarn_packages:
    #   - react-native-cli
    #   - create-react-app
    #   - apollo
    #   - generator-generator
    #   - yo
    dotfiles_repo: "https://github.com/mat-green/dotfiles.git"
    dotfiles_repo_version: main
    dotfiles_files:
      - .zshrc.personal.before
      - .zshrc.personal.after
    homebrew_cask_apps: # Search https://formulae.brew.sh/ for apps 
      - adoptopenjdk8 # AKA java (required by ubiquiti-unifi-controller), password
      - adobe-acrobat-reader # password
      - canon-captureontouch-utility # password
      - ubiquiti-unifi-controller # Password
      - virtualbox # Password
      - android-file-transfer
      - apache-directory-studio
      - drawio
      - docker
      - dropbox
      - balenaetcher
      - firefox
      - flux
      - gimp
      - google-chrome
      - grammarly
      - kindle
      - iterm2
      - lastpass
      - lens
      - leocad
      - libreoffice
      - logseq
      - pgadmin4
      - rescuetime
      - signal
      - slack
      - spotify
      - steam
      - telegram
      - vlc
      - visual-studio-code
      - vivaldi
      - whatsapp
      - zoom
    homebrew_installed_packages:  # Search https://formulae.brew.sh/ for packages
      - asdf
      - gnu-tar
      - gpg
      - gawk
      - htop
      - mas
      - packer
      - postgresql
      - pnpm
      - syncthing
      - terraform-ls
      - unzip
      - zsh
    homebrew_uninstalled_packages: []
    homebrew_taps:
      - homebrew/cask-drivers
      - homebrew/cask-versions
    mas_signin_dialog: true
    mas_installed_apps:
      - { id: 406056744, name: "Evernote (7.14)" }
      - { id: 402592703, name: "Time Out (2.6.2)" }
      - { id: 441258766, name: "Magnet (2.4.9)" }
    mas_uninstalled_apps:
      - { id: 408981434, name: "iMovie" }
      - { id: 409183694, name: "Keynote" }
      - { id: 409201541, name: "Pages" }
      - { id: 409203825, name: "Numbers" }
      - { id: 682658836, name: "GarageBand" }
    java_supplier: adoptopenjdk-8
    vscode_extensions:
      - Shan.code-settings-sync

# Need to stop the mac from sleeping, see http://www.rawinfopages.com/mac/how-to-customise-power-settings-terminal-mac, during the install.
  roles:
    - geerlingguy.mac.homebrew
    - homebrew
    - geerlingguy.mac.mas
    - geerlingguy.dotfiles
    - oh-my-zsh
    - asdf
    - vscode
    - patches
