---
- name: Adding apt key for repository
  become: yes
  apt_key:
    url: "{{ item.key_url }}"
    state: present
  when: item.key_url is defined
  with_items: "{{ apt_repositories }}"
  tags: packages

- name: Adding apt repository
  become: yes
  apt_repository:
    repo: "{{ item.sources_entry }}"
    state: present
    update_cache: no
  with_items: "{{ apt_repositories }}"
  tags: packages

- name: Updating apt cache
  become: yes
  apt:
    update_cache: yes
  tags: packages

- name: Manage package
  become: yes
  apt:
    pkg: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{apt_packages }}"
  tags: packages

- name: Manage debian package
  become: yes
  apt:
    deb: "{{ item.url }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ apt_deb_packages }}"
  tags: packages
