---
- name: Ensure User Configuration Folder Exists
  file: 
    path: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User"
    owner: "{{ lookup('env', 'USER') }}"
    recurse: yes
    state: directory

- name: Create a default VSCode configuration
  template:
    src: templates/vscode-settings.json.j2
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/settings.json"
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: Create a default VSCode keuybinding configuration
  template:
    src: templates/vscode-keybindings.json.j2
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/keybindings.json"
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

# Add something which ensures path is set here
- name: Install VSCode extensions
  shell: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"

