---

- name: Ensure flatpak remotes are installed
  become: false
  community.general.flatpak_remote:
    name: unfiltered-flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

