- name: Get page with kernel packages listed
  ansible.builtin.uri:
    url: "https://kernel.ubuntu.com/~kernel-ppa/mainline/v{{ kernel_version }}/{{ kernel_arch }}/"
    return_content: true
  register: kernel_page

- name: Install kernel dependency
  become: yes
  ansible.builtin.apt:
    deb: http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.38-1ubuntu4_amd64.deb

- name: Install kernel headers packages
  become: yes
  ansible.builtin.apt:
    deb: "https://kernel.ubuntu.com/~kernel-ppa/mainline/v{{ kernel_version }}/{{ kernel_arch }}/{{ item }}"
  with_items:
    - "{{ kernel_page | regex_findall('(linux-headers[a-z0-9-_\\.]+all.deb)', ignorecase=True) | unique }}"

- name: Install kernel arch headers package
  become: yes
  ansible.builtin.apt:
    deb: "https://kernel.ubuntu.com/~kernel-ppa/mainline/v{{ kernel_version }}/{{ kernel_arch }}/{{ item }}"
  with_items:
    - "{{ kernel_page | regex_findall('(linux-headers[a-z0-9-_\\.]+{{ kernel_arch }}.deb)', ignorecase=True) | unique }}"

- name: Install kernel modules package
  become: yes
  ansible.builtin.apt:
    deb: "https://kernel.ubuntu.com/~kernel-ppa/mainline/v{{ kernel_version }}/{{ kernel_arch }}/{{ item }}"
  with_items:
    - "{{ kernel_page | regex_findall('(linux-modules[a-z0-9-_\\.]+{{ kernel_arch }}.deb)', ignorecase=True) | unique }}"

- name: Install kernel modules package
  become: yes
  ansible.builtin.apt:
    deb: "https://kernel.ubuntu.com/~kernel-ppa/mainline/v{{ kernel_version }}/{{ kernel_arch }}/{{ item }}"
  with_items:
    - "{{ kernel_page | regex_findall('(linux-image-unsigned[a-z0-9-_\\.]+{{ kernel_arch }}.deb)', ignorecase=True) | unique }}"

