---
- name: "Include {{ ansible_facts['distribution'] }} {{ kernel_version }} tasks"
  include_tasks: "{{ ansible_facts['distribution'] | replace(' ', '') }}/{{ kernel_version | regex_search('([0-9]+.[0-9]+)') }}.yml"
  
- name: Add Mainline Tool repository to sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:cappelikan/ppa
    state: present

- name: Install mainline tool
  become: yes
  ansible.builtin.apt:
    name: mainline

# Install kernel using Mainline application.

