---
- name: "Include {{ ansible_facts['distribution'] }} {{ kernel_version }} tasks"
  include_tasks: "{{ ansible_facts['distribution'] | replace(' ', '') }}/{{ kernel_version | regex_search('([0-9]+.[0-9]+)') }}.yml"
  
- name: Download ubuntu mainline kernel management file
  become: yes
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh
    dest: "/usr/local/bin/ubuntu-mainline-kernel.sh"
    mode: u=rwx,g=r,o=r

# kernel version check?

- name: Install kernel version
  become: yes
  ansible.builtin.shell: "ubuntu-mainline-kernel.sh --yes -i {{ kernel_version }}"
  notify:
    - Restart system

