---
- name: Install ZSH Shell
  block:
    - name: Install zsh package
      ansible.builtin.package:
        name: zsh
        state: present
 
    - name: Ensure basic .zshrc is in home directory
      copy:
        content: ""
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"
        force: false
        group: "{{ lookup('env', 'USER') }}"
        owner: "{{ lookup('env', 'USER') }}"
        mode: 0644
      
    - name: Get the path to shell
      ansible.builtin.shell: which zsh
      register: shell_path

    - name: Ensure shell is in allowed shells
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: "{{ shell_path.stdout }}"
      when: shell_path is not skipped

    - name: Set shell as the default shell
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        shell: "{{ shell_path.stdout }}"
      when: shell_path is not skipped
      notify:
        - Restart session
  become: true
  when: lookup('env', 'SHELL') is not contains('zsh')

- name: Install Oh My ZSH
  block:
    - name: Install supporting oh-my-zsh packages
      become: true
      ansible.builtin.package:
        name: git
        state: present
    
    - name: Create temporary file
      ansible.builtin.tempfile:
        state: directory
      register: ohmyzsh_temp

    - name: Download Oh My Zsh installation file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "{{ ohmyzsh_temp.path }}/install.sh"
        mode: u=rwx,g=r,o=r

    - name: Install Oh My ZSH
      ansible.builtin.shell: ./install.sh
      args:
        chdir: "{{ ohmyzsh_temp.path }}"
        creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"

    - name: Update current session
      ansible.builtin.shell: "{{ansible_user_shell}} -c 'source {{ lookup('env', 'HOME') }}/.zshrc'"
  when: lookup('env', 'SHELL') is contains('zsh')

