- name: Create temporary file
  ansible.builtin.tempfile:
    state: directory
  register: homebrew_temp

- name: Download Homebrew installation file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: "{{ homebrew_temp.path }}/install.sh"
    mode: u=rwx,g=r,o=r

- name: Install Homebrew on Linux
  ansible.builtin.shell: ./install.sh
  args:
    chdir: "{{ homebrew_temp.path }}"
    creates: /home/linuxbrew/.linuxbrew

- name: Check Homebrew on Linux
  ansible.builtin.shell: test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

- name: Ensure profile file is updated.
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: echo "eval \"\$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\"" >> ~/.profile

- name: Install Homebrew bottled applications
  community.general.homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ homebrew_bottles }}"

- name: Install Homebrew cask applications
  community.general.homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ homebrew_casks }}"
