---
- name: "Make sure homebrew bin is in path"
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root

- name: "add custom homebrew repos"
  community.general.homebrew_tap:
    name: homebrew_taps

- name: "Install core packages via brew casks"
  community.general.homebrew_cask:
    name: homebrew_casks
    ignore_errors: yes

- name: "Install homebrew packages"
  community.general.homebrew:
    name: homebrew_packages
    state: present
    update_homebrew: yes
