# Reference https://forum.zorin.com/t/how-to-upgrade-zorin-16-2-to-a-newer-kernel/24102
#- name: Add Mainline Tool repository to sources list
#  become: yes
#  ansible.builtin.apt_repository:
#    repo: ppa:cappelikan/ppa
#    state: present

#- name: Install mainline tool
#  become: yes
#  ansible.builtin.apt:
#    name: mainline

- block:
  - name: Add Upstream repository to sources list
    become: yes
    ansible.builtin.apt_repository:
      repo: deb http://ca.archive.ubuntu.com/ubuntu mantic main universe restricted
      state: present

  - name: Install supporting packages for kernal 6.4
    become: yes
    ansible.builtin.apt:
      name:
        #- libc6
        - libssl3
        - gcc-12
      state: latest
      
  - name: Remove Upstream repository to sources list
    become: yes
    ansible.builtin.apt_repository:
      repo: deb http://ca.archive.ubuntu.com/ubuntu mantic main universe restricted
      state: absent

  - name: Create alternatives to gcc
    become: yes
    community.general.alternatives:
      name: gcc
      link: /usr/bin/gcc
      path: /usr/bin/gcc-12
      priority: 20
      subcommands:
        - name: "g++"
          link: "/usr/bin/g++"
          path: "/usr/bin/g++-12"

  when: ansible_facts['distribution_version'] is version('16', '<=')



