- name: Create temporary file
  ansible.builtin.tempfile:
    state: directory
  register: xpandneo_temp
  
- name: Get latest release of Xpadneo
  ansible.builtin.git:
    repo: 'https://github.com/atar-axis/xpadneo.git'
    dest: "{{ xpandneo_temp.path }}"

- name: Install XBox controller drivers
  become: yes
  ansible.builtin.shell: ./install.sh
  args:
    chdir: "{{ xpandneo_temp.path }}"
    creates: /var/lib/dkms/hid-xpadneo/

